sudo: required
dist: trusty
language: python
cache: pip
services:
  - docker
  - redis
python:
    - "3.5"
env:
  global:
     - OK_ENV=test
  matrix:
    - SETUP=docker
    - SETUP=native
install:
  - if [ "$SETUP" = "docker" ]; then make docker-build; fi
  - if [ "$SETUP" = "native" ]; then pip install -r requirements.txt; fi
  - if [ "$SETUP" = "native" ]; then pip install pytest-timeout python-coveralls; fi
script:
  - if [ "$SETUP" = "docker" ]; then docker run -it cs61a/ok-server py.test tests/; fi
  - if [ "$SETUP" = "native" ]; then py.test --cov-report term-missing --cov=server tests/  --ignore tests/test_web.py --timeout=30; fi
after_success:
  - if [ "$SETUP" = "native" ]; then echo "eventually should run coveralls here"; fi
notifications:
  email: false
  slack:
    on_success: never
    on_failure: always
    secure: mGqCgRCFMB89AKsYVOZI79sifCFOLaQkuY3rvFKMitpD1GYQQpkBbZ9Z1SWi0VQV63oOKTQBrPCeDSwhZMaJA/dCZZIuz6e9nkVyJJUIrqAuH9PjgQr6FM4FkKzVLpHdPnXIikAvUAKiPRzzj8z4KO1EohBRR/xb2/4TpoWrkSA=
